### ISSUE TITLE
Wrong LZ4 Compress in `w FILENAME.lz4`

### ISSUE THREAD

**Issue by KSR-Yasuda** [funcodeio/lz4.vim#2]
Writing file by `w FILENAME.lz4`, it does lz4-compression for the current opening file.

1. `:e test.txt`
2. Input something
3. `:w`
    - Now the file `test.txt` is normal (uncompressed) file.
4. `:w %.lz4`
    - Creates `test.txt.lz4` of normal (uncompressed) file.
    - Besides, it overwrites `test.txt` as lz4-compressed data.
    - Rather expected to write lz4-compressed data to `test.txt.lz4`.

```bash
% file *.*
test.txt:     LZ4 compressed data (v1.4+)
test.txt.lz4: ASCII text
```

**Comment by funcodeio** [comment]
Thanks for PR. I guess gzip.vim has the same issue as this code is based on gzip.vim.

**Comment by KSR-Yasuda** [comment]
Thank you for merging.

> I guess gzip.vim has the same issue as this code is based on gzip.vim.

In my env, it did not happen on a gzip file.
Probably it had been fixed already.
